-- AlterTable
ALTER TABLE `profil_user` ADD COLUMN `codePays` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `user` ADD COLUMN `status` ENUM('ACTIVE', 'SUSPENDED', 'DELETED') NOT NULL DEFAULT 'ACTIVE';
